version: '2'

services:
  nsqlookupd:
    image: nsqio/nsq
#    ports:
#    - "4160:4160"
#    - "4161:4161"
    networks:
    - nsq
    command: /nsqlookupd

  nsqd:
    image: nsqio/nsq
#    ports:
#    - "4150:4150"
#    - "4151:4151"
    links:
    - nsqlookupd
    networks:
    - nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160

  nsqadmin:
    image: nsqio/nsq
    ports:
    - "4171:4171"
    links:
    - nsqlookupd
    networks:
    - nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161

networks:
  nsq:
    driver: bridge

